# Generated by Django 5.0.6 on 2024-05-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_transaction_aceecess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='aceecess',
            new_name='access',
        ),
    ]
